name: fashion-bench
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - torchvision
      - numpy<2.3.0
      - nncf==2.19.0
      - openvino==2025.4.1
      - onnx
      - onnxscript
